### ISSUE TITLE
Test: Update room

### ISSUE THREAD

**Issue by kepbautista** [2015firstcmsc100/galadhrim#103]
Add test case suite for PUT /api/rooms/:id.

**Comment by DeborahAbad** [comment]
Pano po ulit isesend ung mga gawa? Tska ano pong files ung kailangan and hanggang kelan po ung deadline? Thanks po.

**Comment by DeborahAbad** [comment]
Wala pong table for rooms, pano po malalaman ung mga kailangan?

**Comment by mightybulacs** [comment]
* the test does not guarantee that the correct record was updated; it merely checked that the returned record has the correct name; for all we know, the implementation of PUT /api/rooms/:id update ALL records with the provided name
* the test does not ensure that the _updated (the timestamp when the record was changed) field was updated
* same comments as above for other items that update a specific property of the record
* the last test case is practically useless since we do not change the id of a record. otherwise, we could have data inconsistencies everywhere
